/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_OverloadSample */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_OverloadSample
#define _Included_xyz_teamgravity_jnidemo_core_sample_OverloadSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    minus
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_minus
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    multiply
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_multiply__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    multiply
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_multiply___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    multiply
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_multiply__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    multiply
 * Signature: (Lxyz/teamgravity/jnidemo/core/sample/OverloadSample;Lxyz/teamgravity/jnidemo/core/sample/OverloadSample;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_multiply__Lxyz_teamgravity_jnidemo_core_sample_OverloadSample_2Lxyz_teamgravity_jnidemo_core_sample_OverloadSample_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    divide_me
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_divide_1me__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    divide_me
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_divide_1me__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    hello
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_hello__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    hello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_hello__I
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
