/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample
#define _Included_xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample
 * Method:    addRegion
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample_addRegion
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample
 * Method:    addElements
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample_addElements
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample
 * Method:    addCritical
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_ArrayCriticalAccessSample_addCritical
  (JNIEnv *, jclass, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
