/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_data_model_PersonModel_Book */

#ifndef _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Book
#define _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Book
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Book
 * Method:    printTitle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Book_printTitle
  (JNIEnv *, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Book
 * Method:    createBook
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel;)Lxyz/teamgravity/jnidemo/data/model/PersonModel/Book;
 */
JNIEXPORT jobject JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Book_createBook
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
