/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_data_model_PeopleModel */

#ifndef _Included_xyz_teamgravity_jnidemo_data_model_PeopleModel
#define _Included_xyz_teamgravity_jnidemo_data_model_PeopleModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PeopleModel
 * Method:    allocate0
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_xyz_teamgravity_jnidemo_data_model_PeopleModel_allocate0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PeopleModel
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PeopleModel_free0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PeopleModel
 * Method:    getName0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_data_model_PeopleModel_getName0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PeopleModel
 * Method:    getAge0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xyz_teamgravity_jnidemo_data_model_PeopleModel_getAge0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PeopleModel
 * Method:    sayHi0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PeopleModel_sayHi0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
