/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_override_Child */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_override_Child
#define _Included_xyz_teamgravity_jnidemo_core_sample_override_Child
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_override_Child
 * Method:    malibu
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_override_Child_malibu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
