/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_data_model_PersonModel_Bag */

#ifndef _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Bag
#define _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Bag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Bag
 * Method:    printSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Bag_printSize__
  (JNIEnv *, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Bag
 * Method:    printSize
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel/Bag;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Bag_printSize__Lxyz_teamgravity_jnidemo_data_model_PersonModel_00024Bag_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Bag
 * Method:    createBag
 * Signature: ()Lxyz/teamgravity/jnidemo/data/model/PersonModel/Bag;
 */
JNIEXPORT jobject JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Bag_createBag
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
