/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_Unsafe */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_Unsafe
#define _Included_xyz_teamgravity_jnidemo_core_util_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    putInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_putInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_getInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    putDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_putDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_Unsafe
 * Method:    getDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_util_Unsafe_getDouble
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
