/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_manager_LoanManager */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_manager_LoanManager
#define _Included_xyz_teamgravity_jnidemo_core_util_manager_LoanManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_LoanManager
 * Method:    calculateExtra
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_LoanManager_calculateExtra
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
