/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_data_model_PersonModel_Book */

#ifndef _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Book
#define _Included_xyz_teamgravity_jnidemo_data_model_PersonModel_Book
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_data_model_PersonModel_Book
 * Method:    printTitle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_data_model_PersonModel_00024Book_printTitle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
