/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample
#define _Included_xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample
 * Method:    printStringRegular
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample_printStringRegular
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample
 * Method:    printStringCritical
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_sample_StringCriticalAccessSample_printStringCritical
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
