/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_OverloadSample */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_OverloadSample
#define _Included_xyz_teamgravity_jnidemo_core_sample_OverloadSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_OverloadSample
 * Method:    add
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_OverloadSample_add__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
