/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_manager_TextManager */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_manager_TextManager
#define _Included_xyz_teamgravity_jnidemo_core_util_manager_TextManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_hello
  (JNIEnv *, jclass);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_print
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    concat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_concat
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    evaluatePerson
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_evaluatePerson
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    divorcePerson
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_divorcePerson
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    printPerson
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_printPerson
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_TextManager
 * Method:    agePeriod
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/PersonModel;)V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_TextManager_agePeriod
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
