/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_FileReader */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_FileReader
#define _Included_xyz_teamgravity_jnidemo_core_util_FileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_FileReader
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_FileReader_initIds
  (JNIEnv *, jclass);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_FileReader
 * Method:    open0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_FileReader_open0
  (JNIEnv *, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_FileReader
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_FileReader_close0
  (JNIEnv *, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_FileReader
 * Method:    next0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_FileReader_next0
  (JNIEnv *, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_FileReader
 * Method:    eof
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xyz_teamgravity_jnidemo_core_util_FileReader_eof
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
