/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_sample_override_Parent */

#ifndef _Included_xyz_teamgravity_jnidemo_core_sample_override_Parent
#define _Included_xyz_teamgravity_jnidemo_core_sample_override_Parent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_sample_override_Parent
 * Method:    mustang
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_sample_override_Parent_mustang
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
