/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_manager_AnimalManager */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
#define _Included_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
 * Method:    speak
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/AnimalModel;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager_speak
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
 * Method:    animalSpeak
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/AnimalModel;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager_animalSpeak
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
 * Method:    dogSpeak
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/AnimalModel;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager_dogSpeak
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_AnimalManager
 * Method:    catSpeak
 * Signature: (Lxyz/teamgravity/jnidemo/data/model/AnimalModel;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_AnimalManager_catSpeak
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
