/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_manager_MathManager */

#ifndef _Included_xyz_teamgravity_jnidemo_core_util_manager_MathManager
#define _Included_xyz_teamgravity_jnidemo_core_util_manager_MathManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_sayHi
  (JNIEnv *, jclass);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    isOdd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_isOdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    damage
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_damage
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
