/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_teamgravity_jnidemo_core_util_manager_MathManager */

#ifndef Included_xyz_teamgravity_jnidemo_core_util_manager_MathManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_sayHi
        (JNIEnv *, jclass);

/*
 * Class:     xyz_teamgravity_jnidemo_core_util_manager_MathManager
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_xyz_teamgravity_jnidemo_core_util_manager_MathManager_multiply
        (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
